# Generated by Django 2.1.3 on 2019-01-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_name', models.CharField(max_length=200)),
                ('col_address', models.CharField(max_length=200)),
            ],
        ),
    ]
