# Generated by Django 2.1.3 on 2019-01-26 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campusrecruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_coll', models.CharField(max_length=200)),
                ('roll_no', models.CharField(max_length=200)),
                ('student_gpa', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='recruitment',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
